name: legend_design_core
description: A package containing the Core Functionalites of the Legend Design ecosystem.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  flutter_hooks: ^0.18.5+1
  google_fonts: ^2.1.0
  animations: ^2.0.2
  http: ^0.13.4
  flutter_svg: ^1.1.0
  legend_utils:
    git: 
      url: https://github.com/ThomasFercher/legend_utils
  legend_router:
    path: ../legend_router
    #git:
      #url: https://github.com/ThomasFercher/legend_router
  legend_annotations:
    git: 
      url: https://github.com/ThomasFercher/legend_annotations


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  legend_generator:
    path: ../CodeGen/legend_generator
  test: ^1.0.0
flutter:

